version: '3.5'

services:
  mongodb:
    container_name: workcode-database
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - workcode-api
  mailhog:
    container_name: workcode-SMTP
    image: mailhog/mailhog
    ports:
      - 1025:1025 # SMTP Server
      - 8025:8025 # UI
    restart: unless-stopped
    logging:
      driver: 'none'
    networks:
      - workcode-api
  server:
    container_name: workcode-server
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mongodb
      - mailhog
    env_file:
      - ./.env
    networks:
      - workcode-api

networks:
  workcode-api:
    driver: bridge
