version: '3.5'

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # SMTP Server
      - 8025:8025 # UI
    restart: unless-stopped
    logging:
      driver: 'none'
